export const FETCH_LIST_DATA = 'FETCH_LIST_DATA';
export const FETCH_LIST_DATA_SUCCESS = 'FETCH_LIST_DATA_SUCCESS';
export const FETCH_LIST_DATA_FAILURE = 'FETCH_LIST_DATA_FAILURE';

export const FETCH_CAT_DATA = 'FETCH_CAT_DATA';
export const FETCH_CAT_DATA_SUCCESS = 'FETCH_CAT_DATA_SUCCESS';
export const FETCH_CAT_DATA_FAILURE = 'FETCH_CAT_DATA_FAILURE';
